import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { ThemeProvider } from "../utils/theme-provider";
import TopNavigation from "@/components/Navigation/TopNavigation";
import SideNavigation from "@/components/Navigation/SideNavigation";
import StateContextProvider from "./stateManager/context";
=======
>>>>>>> 9934ae0 (Initial commit from Create Next App)

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
<<<<<<< HEAD
  title: "FindJobs",
  description: "Find your dream Job",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 9934ae0 (Initial commit from Create Next App)
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <StateContextProvider>
        <ThemeProvider attribute="class" defaulTheme="system" enableSystem>
          <body className={inter.className}>
            <main className=" ">
              <div className="conten relative">
                <TopNavigation />

                {children}
              </div>
            </main>
          </body>
        </ThemeProvider>
      </StateContextProvider>
=======
      <body className={inter.className}>{children}</body>
>>>>>>> 9934ae0 (Initial commit from Create Next App)
    </html>
  );
}
